# Generated by Django 4.2.17 on 2024-12-17 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cart_food_order_alter_comment_date_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 17, 16, 57, 43, 952364), verbose_name='Дата комментария'),
        ),
    ]
