# Generated by Django 4.2.17 on 2024-12-17 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_comment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['posted'], 'verbose_name': 'блюдо из меню', 'verbose_name_plural': 'блюдо из меню'},
        ),
        migrations.AddField(
            model_name='food',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 17, 19, 22, 57, 355400), verbose_name='Дата комментария'),
        ),
        migrations.AlterModelTable(
            name='food',
            table='Foods',
        ),
    ]
