# Generated by Django 4.2.17 on 2024-12-26 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_remove_userprofile_user_remove_cartitem_food_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'услуги', 'verbose_name_plural': 'услуга'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 26, 21, 9, 25, 412604), verbose_name='Дата комментария'),
        ),
    ]
