# Generated by Django 4.2.17 on 2024-12-26 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_comment_date_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 26, 21, 18, 53, 865246), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к изображению'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
    ]
